version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      -   app
    container_name: nutgrumbot_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        -   db
    container_name: nutgrumbot_app

  db:
      image: postgres:15.3
      restart: always
      volumes:
          -   ./tmp/db:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: root
      ports:
          - "5432:5432"
      container_name: nutgrumbot_db
  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080
